
name: Build QuickFIX with Cosmopolitan Libc

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout QuickFIX
      run: |
        git clone https://github.com/quickfix/quickfix.git
        cd quickfix
        git checkout master

    - name: Set up Cosmopolitan Libc
      run: |
        mkdir -p cosmocc
        cd cosmocc
        wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
        unzip cosmocc.zip

    - name: Set environment variables
      run: |
        echo "CC=$(pwd)/cosmocc/cosmocc" >> $GITHUB_ENV
        echo "CXX=$(pwd)/cosmocc/cosmoc++" >> $GITHUB_ENV

    - name: Build QuickFIX
      run: |
        cd quickfix
        ./bootstrap
        ./configure --prefix=/opt/cosmos/x86_64
        make -j
        make install
